openapi: 3.0.3
info:
  title: Rating App
  description: This is the API for the Rating App
  version: 1.0.0
tags:
  - name: topic
  - name: ratable
  - name: rating
  - name: user
paths:
  /topic:
    get:
      summary: Fetch all topics
      description: Retreive all topics of rating app
      tags: 
        - topic
      parameters:
        - name: filter
          in: query
          description: Filter on name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'
        '400':
          description: Invalid status value
    post:
      summary: Create a topic
      description: Create a topic of the rating app
      tags: 
        - topic
      requestBody:
        description: Topic to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Topic'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Topic'
        '400':
          description: Invalid status value
  /topic/{topicId}: 
    parameters:
      - name: topicId
        in: path
        description: Name of the topic
        required: true
        schema:
          type: string
    delete:
      summary: Delete a topic
      description: Delete a topic of the rating app
      tags: 
        - topic
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Topic'
        '400':
          description: Invalid status value
  /topic/{topicId}/ratable:
    parameters:
      - name: topicId
        in: path
        description: Name of the topic
        required: true
        schema:
          type: string
    get:
      summary: Fetch all ratables
      description: Retreive all ratables of a topic
      tags: 
        - ratable
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Invalid status value
    post:
      summary: Create a ratable
      description: Create a ratable of a topic
      tags: 
        - ratable
      requestBody:
        description: Ratable to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ratable'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ratable'
        '400':
          description: Invalid status value
  /topic/{topicId}/ratable/{ratableId}:
    parameters:
      - name: topicId
        in: path
        description: Name of the topic
        required: true
        schema:
          type: string
      - name: ratableId
        in: path
        description: Name of the ratable
        required: true
        schema:
          type: string
    get:
      summary: Fetch a ratable
      description: Retreive a ratable of a topic
      tags: 
        - ratable
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ratable'
        '400':
          description: Invalid status value
    put:
      summary: Update a ratable
      description: Update a ratable of a topic
      tags: 
        - ratable
      requestBody:
        description: Ratable to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ratable'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ratable'
        '400':
          description: Invalid status value
    delete:
      summary: Delete a ratable
      description: Delete a ratable of a topic
      tags: 
        - ratable
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ratable'
        '400':
          description: Invalid status value
  /topic/{topicId}/ratable/{ratableId}/rating:
    parameters:
      - name: topicId
        in: path
        description: Name of the topic
        required: true
        schema:
          type: string
      - name: ratableId
        in: path
        description: Name of ratable
        required: true
        schema:
          type: string
    post:
      summary: Create a rating
      description: Create a rating of a ratable
      tags: 
        - rating
      requestBody:
        description: Rating
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rating'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
        '400':
          description: Invalid status value
  /topic/{topicId}/ratable/{ratableId}/rating/{ratingId}:
    parameters:
      - name: topicId
        in: path
        description: Name of the topic
        required: true
        schema:
          type: string
      - name: ratableId
        in: path
        description: Name of the ratable
        required: true
        schema:
          type: string
      - name: ratingId
        in: path
        description: Id of the rating
        required: true
        schema:
          type: string
    delete:
      summary: Delete a rating
      description: Delete a rating of a ratable
      tags: 
        - rating
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
        '400':
          description: Invalid status value
  /register:
    post:
      summary: Register
      description: Register
      tags: 
        - user
      requestBody:
        description: User to register
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
        '400':
          description: Invalid status value
  /login:
    post:
      summary: Login
      description: Login
      tags: 
        - user
      requestBody:
        description: User to login
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
        '400':
          description: Invalid status value
components:
  schemas:
    Topic:
      type: object
      required:
        - topicId
      properties:
        topicId:
          type: string
    Ratable:
      type: object
      required:
        - ratableId
        - ratableName
        - description
        - image
      properties:
        ratableId:
          type: string
        ratableName:
          type: string
        description:
          type: string
        image:
          type: string
    Rating:
      type: object
      required:
        - ratingId
        - score
      properties:
        ratingId:
          type: string
        score:
          type: number
          format: float
